package com.chamasmart.backend;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@SpringBootApplication
@EnableTransactionManagement
@EnableScheduling
public class ChamaSmartApplication {

    public static void main(String[] args) {
        SpringApplication.run(ChamaSmartApplication.class, args);
    }

    @Bean
    public CommandLineRunner resetSequences(JdbcTemplate jdbcTemplate) {
        return args -> {
            // First, dynamically add missing version columns
            String[] versionTables = {"chamas", "loans", "welfare_fund", "welfare_claims", "asca_cycles"};
            for (String table : versionTables) {
                try {
                    String sql = "ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS version bigint DEFAULT 0";
                    jdbcTemplate.execute(sql);
                    System.out.println("Successfully ensured version column exists on table: " + table);
                } catch (Exception e) {
                    System.out.println("Could not add version column to " + table + ": " + e.getMessage());
                }
            }

            // Ensure meetings table has all required columns
            try {
                jdbcTemplate.execute("ALTER TABLE meetings ADD COLUMN IF NOT EXISTS recorded_by bigint");
                jdbcTemplate.execute("ALTER TABLE meetings ADD COLUMN IF NOT EXISTS meeting_link text");
                System.out.println("Successfully ensured meetings columns exist");
            } catch (Exception e) {
                System.out.println("Could not ensure meetings columns: " + e.getMessage());
            }

            // Ensure contributions table has payment_proof and notes columns
            try {
                jdbcTemplate.execute("ALTER TABLE contributions ADD COLUMN IF NOT EXISTS payment_proof varchar(500)");
                jdbcTemplate.execute("ALTER TABLE contributions ADD COLUMN IF NOT EXISTS notes text");
                System.out.println("Successfully ensured contributions payment_proof and notes columns exist");
            } catch (Exception e) {
                System.out.println("Could not ensure contributions payment_proof and notes columns: " + e.getMessage());
            }

            // Ensure chamas meeting_day length is expanded to varchar(255)
            try {
                jdbcTemplate.execute("ALTER TABLE chamas ALTER COLUMN meeting_day TYPE varchar(255)");
                System.out.println("Successfully altered chamas.meeting_day length to 255");
            } catch (Exception e) {
                System.out.println("Could not alter chamas.meeting_day length: " + e.getMessage());
            }

            // Ensure mpesa_transactions table sequence column exists
            try {
                jdbcTemplate.execute("ALTER TABLE mpesa_transactions ADD COLUMN IF NOT EXISTS transaction_id bigint GENERATED BY DEFAULT AS IDENTITY");
            } catch (Exception e) {
                // column likely already exists, ignore
            }

            // Second, reset the serial sequences
            String[] tables = {"users", "chamas", "chama_members", "loans", "contributions", "meetings", "welfare_fund", "welfare_claims", "asca_cycles", "mpesa_transactions"};
            String[] idColumns = {"user_id", "chama_id", "membership_id", "loan_id", "contribution_id", "meeting_id", "fund_id", "claim_id", "cycle_id", "transaction_id"};
            
            for (int i = 0; i < tables.length; i++) {
                String table = tables[i];
                String idCol = idColumns[i];
                try {
                    String sql = "SELECT setval(pg_get_serial_sequence('" + table + "', '" + idCol + "'), COALESCE(MAX(" + idCol + "), 1)) FROM " + table;
                    jdbcTemplate.execute(sql);
                    System.out.println("Successfully reset sequence for " + table + "." + idCol);
                } catch (Exception e) {
                    System.out.println("Could not reset sequence for " + table + ": " + e.getMessage());
                }
            }
        };
    }

}
